server:
  port: 8088

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      prod:
        #基本属性
        name: prod
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/selfrecordmgt?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        username: root
        password: admin
      dev:
        #基本属性
        name: prod
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/selfrecordmgt_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        username: root
        password: admin


mybatis:
  type-aliases-package: com.tanjie.selfrecordmgt.dao
  mapper-locations: classpath*:mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


# 打印sql
logging:
  level:
    com.tanjie.selfrecordmgt.dao: debug


#Spring Security 相关设置
# token 请求头的名字
token:
  header: token
  # token 加密密钥
  secret: secret
  # token 过期时间，以秒为单位，604800 是 一星期  86400
  expiration: 86400

swagger2:
  enable: true


#  #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
#    mvc:
#      throw-exception-if-no-handler-found: true
#  #不要为我们工程中的资源文件建立映射
resources:
  add-mappings: true